name: Windmill Test & Deploy, add
# another change: 1
on:
  push:
    branches: [ main ]
    paths:
      - 'u/doronw/**'
      - '.github/workflows/CD.yaml'
env:
  WMILL_TOKEN: ${{ secrets.WMILL_TOKEN }}
  EMAIL: ${{ vars.EMAIL }}
  SHIPPING_ADDRESS: '{"first_name": "doron", "last_name": "weiss", "address_1": "shushan tzahor 4", "postal_code": "11111", "city": "tzoran", "country_code": "il"}'
  ITEMS: '[{"sku": "test3-red-s","quantity": 2},{"sku": "test3-blue-l","quantity": 1}]'
  REGION_ID: ${{ vars.REGION_ID }}
  BASE_URL: https://workflow.retail-os.ai/
  WORKSPACE: retailos

jobs:
  test-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Windmill CLI
        run: npm install -g windmill-cli

      - name: Push to Test Path
        # Maps local u/doronw to remote u/doronw_test
        run: |
          wmill sync push --includes "u/doronw/creating_order_webhook_test,u/doronw/checkout_steps_test" --token "${{ env.WMILL_TOKEN }}" --base-url "${{ env.BASE_URL }}" --workspace "${{ env.WORKSPACE }}" --yes

      - name: Run Webhook Test
        # Executes the flow/script located at the test path
        # Adjust the --data JSON if your webhook requires specific inputs
        run: |
          echo "Executing test run for u/doronw/webhook_test..."
          wmill flow run creating_order_webhook_test --data '{ "email": "${{ env.EMAIL }}", "shipping_address": ${{ env.SHIPPING_ADDRESS }}, "items": ${{ env.ITEMS }}, "region_id": "${{ env.REGION_ID }}" }' --token "${{ env.WMILL_TOKEN }}" --base-url "${{ env.BASE_URL }}" --workspace "${{ env.WORKSPACE }}"
          